[package]
name = "drv-stm32h7-usart"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib"}
zerocopy = "0.6.1"
num-traits = { version = "0.2.12", default-features = false }
drv-stm32xx-sys-api = {path = "../stm32xx-sys-api", default-features = false}
stm32h7 = { version = "0.14.0", default-features = false }
cortex-m = { version = "0.7", features = ["inline-asm"] }

[features]
h743 = ["stm32h7/stm32h743", "drv-stm32xx-sys-api/h743"]
h753 = ["stm32h7/stm32h753", "drv-stm32xx-sys-api/h753"]

[lib]
name = "drv_stm32h7_usart"
test = false
bench = false
crate_type = ["staticlib"]
